security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity: { class: App\Entity\User, property: email }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        page:
            provider: app_user_provider
            lazy: true
            form_login:
                check_path: security_login
                login_path: security_login
                default_target_path: index
                enable_csrf: true
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: security_logout
                target: security_login
            entry_point: App\Security\AuthenticationEntryPoint
            access_denied_handler: App\Security\AccessDeniedHandler
            custom_authenticators:
                - App\Security\SecurityAuthenticator
    #      login_throttling:
    #        max_attempts: 3
    #        interval: '15 minutes'
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }